# This is a basic workflow to help you get started with Actions

name: Gradle Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gradle-build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build


  github-pages-deploy:
    needs: gradle-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gh-pages-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gh-pages-
            ${{ runner.os }}-

      - name: Run 'dokkaHtml' Gradle task
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: dokkaHtml

      - name: Move Dokka to /docs
        run: cp ./build/dokka/html ./docs

      - name: Rename docs/html folder
        run: ren ./docs/html kotlin-docs

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          BRANCH: gh-pages
          FOLDER: docs